#!/usr/bin/env bash
# Changes the home IP address and updates the hosts file accordingly.

cp /etc/hosts /tmp/hosts.bak

cat << EOF | tee /etc/hosts > /dev/null
127.0.0.2 localhost
8.8.8.8 facebook.com
EOF

echo "Hosts file updated successfully."