#!/usr/bin/env bash
# This script lists all attached IP addresses on the system.

ifconfig | grep -oE 'inet (addr:)?([0-9]{1,3}\.){3}[0-9]{1,3}' \
         | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' \
         | grep -v '^127\..*\.0\.1$' \
         ; echo 127.0.0.1